# Site settings
encoding: UTF-8
title: 时代透镜
subtitle: 留言板
email: chinatimeline@mail2tor.com
description: 可匿名留言，有频率限制，如遇到错误请稍后再提交。
baseurl: "/submit"
url: "https://chinatimeline.github.io/"
locale: en
github_username:  chinatimeline

# Build settings
markdown: kramdown

staticman:
  api: "https://staticman3.herokuapp.com/v3/entry/github/chinatimeline/submit/master/comments"
  path: "_data/events/test-slug"
